import { MaterialCommunityIcons } from '@expo/vector-icons';

export type IconName = React.ComponentProps<typeof MaterialCommunityIcons>['name'];

export const getCategoryIcon = (categoryName: string): IconName => {
  const iconMap: { [key: string]: IconName } = {
    'Alpine Ski': 'ski-cross-country',
    'Backcountry Ski': 'ski-cross-country',
    'Badminton': 'badminton',
    'Canoeing': 'sail-boat',
    'Crossfit': 'dumbbell',
    'E-Bike Ride': 'bicycle-electric',
    'Elliptical': 'sync',
    'E-Mountain Bike Ride': 'bicycle-electric',
    'Golf': 'golf',
    'Gravel Ride': 'bicycle',
    'Handcycle': 'bicycle-basket',
    'High Intensity Interval Training': 'lightning-bolt',
    'Hike': 'hiking',
    'Ice Skate': 'skate',
    'Inline Skate': 'rollerblade',
    'Kayaking': 'sail-boat',
    'Kitesurf': 'kitesurfing',
    'Mountain Bike Ride': 'bicycle',
    'Nordic Ski': 'ski-cross-country',
    'Pickleball': 'tennis',
    'Pilates': 'yoga',
    'Racquetball': 'tennis',
    'Ride': 'bicycle',
    'Rock Climbing': 'terrain',
    'Roller Ski': 'rollerblade',
    'Rowing': 'rowing',
    'Run': 'run-fast',
    'Sail': 'sail-boat',
    'Skateboard': 'skateboarding',
    'Snowboard': 'snowboard',
    'Snowshoe': 'snowflake',
    'Soccer': 'soccer',
    'Squash': 'tennis',
    'Stair Stepper': 'stairs',
    'Stand Up Paddling': 'sail-boat',
    'Surfing': 'surfing',
    'Swim': 'swim',
    'Table Tennis': 'table-tennis',
    'Tennis': 'tennis',
    'Trail Run': 'run-fast',
    'Velomobile': 'car-sports',
    'Walk': 'walk',
    'Weight Training': 'weight',
    'Wheelchair': 'wheelchair-accessibility',
    'Windsurf': 'surfing',
    'Workout': 'dumbbell',
    'Yoga': 'yoga'
  };

  return iconMap[categoryName] || 'dumbbell';
};

export const getCategoryColor = (categoryName: string): string => {
  const colorMap: { [key: string]: string } = {
    'Alpine Ski': '#4FB9AF',
    'Backcountry Ski': '#6B63FF',
    'Badminton': '#6BCB77',
    'Canoeing': '#FF6B6B',
    'Crossfit': '#FFB347',
    'E-Bike Ride': '#9B59B6',
    'Elliptical': '#3498DB',
    'E-Mountain Bike Ride': '#E74C3C',
    'Golf': '#2ECC71',
    'Gravel Ride': '#F1C40F',
    'Handcycle': '#4FB9AF',
    'High Intensity Interval Training': '#6B63FF',
    'Hike': '#6BCB77',
    'Ice Skate': '#FF6B6B',
    'Inline Skate': '#FFB347',
    'Kayaking': '#9B59B6',
    'Kitesurf': '#3498DB',
    'Mountain Bike Ride': '#E74C3C',
    'Nordic Ski': '#2ECC71',
    'Pickleball': '#F1C40F',
    'Pilates': '#4FB9AF',
    'Racquetball': '#6B63FF',
    'Ride': '#6BCB77',
    'Rock Climbing': '#FF6B6B',
    'Roller Ski': '#FFB347',
    'Rowing': '#9B59B6',
    'Run': '#3498DB',
    'Sail': '#E74C3C',
    'Skateboard': '#2ECC71',
    'Snowboard': '#F1C40F',
    'Snowshoe': '#4FB9AF',
    'Soccer': '#6B63FF',
    'Squash': '#6BCB77',
    'Stair Stepper': '#FF6B6B',
    'Stand Up Paddling': '#FFB347',
    'Surfing': '#9B59B6',
    'Swim': '#3498DB',
    'Table Tennis': '#E74C3C',
    'Tennis': '#2ECC71',
    'Trail Run': '#F1C40F',
    'Velomobile': '#4FB9AF',
    'Walk': '#6B63FF',
    'Weight Training': '#6BCB77',
    'Wheelchair': '#FF6B6B',
    'Windsurf': '#FFB347',
    'Workout': '#9B59B6',
    'Yoga': '#3498DB'
  };

  return colorMap[categoryName] || '#4FB9AF';
}; 